[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vassi"
version = "0.0.1"
dependencies = [
    "tbb ; platform_system != 'Darwin'",
    "numba",
    "numpy>=2.0",
    "h5py",
    "pandas",
    "pandas-stubs",
    "tables",
    "matplotlib",
    "scikit-learn",
    "xgboost",
    "networkx",
    "loky",
    "loguru",
    "optuna",
    "observation-library @ git+https://github.com/pnuehrenberg/observation-library.git",
    "jupyterlab",
    "tqdm",
    "kaggle>=1.7.4.5",
    "pyarrow>=21.0.0",
    "fastparquet>=2024.11.0",
    "pip>=25.2",
    "ipympl>=0.9.7",
    "joblib-stubs>=1.5.2.0.20250831",
    "h5py-stubs>=0.1.2",
    "mpi4py>=4.1.1",
]
requires-python = ">=3.12"

[project.optional-dependencies]
docs = [
    "sphinx",
    "sphinx-copybutton",
    "jupyter-sphinx",
    "nbsphinx",
    "shibuya",
    "sphinx_autodoc_typehints",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
# This will disable the 'reportAny' check project-wide
reportAny = "none"
reportUnreachable = "none"
reportMissingTypeStubs = "none"

[tool.ruff]
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
ignore = ["D100", "D101", "D102", "D104", "D103", "D105"]

[tool.ruff.lint.pydocstyle]
convention = "numpy" # Accepts: "google", "numpy", or "pep257".

[tool.ruff.format]
docstring-code-format = true

[tool.uv.sources]
transformations = { path = "../transformations" }

[dependency-groups]
dev = [
    "ruff>=0.14.4",
]
