individual:
- - speed
  - step: 5
    keypoints:
    - 0
    - 3
    - 6
- - speed
  - step: 15
    keypoints:
    - 0
    - 3
    - 6
- - speed
  - step: 30
    keypoints:
    - 0
    - 3
    - 6
- - projected_velocity
  - step: 5
    keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoint_pairs_2:
    - - 6
      - 3
    discard: -rej
- - projected_velocity
  - step: 5
    keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoint_pairs_2:
    - - 6
      - 3
    as_absolute: true
    discard: -proj
- - projected_velocity
  - step: 15
    keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoint_pairs_2:
    - - 6
      - 3
    discard: -rej
- - projected_velocity
  - step: 15
    keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoint_pairs_2:
    - - 6
      - 3
    as_absolute: true
    discard: -proj
- - projected_velocity
  - step: 30
    keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoint_pairs_2:
    - - 6
      - 3
    discard: -rej
- - projected_velocity
  - step: 30
    keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoint_pairs_2:
    - - 6
      - 3
    as_absolute: true
    discard: -proj
- - orientation_change
  - step: 5
    keypoint_pairs:
    - - 3
      - 0
    - - 6
      - 3
    as_absolute: true
- - orientation_change
  - step: 15
    keypoint_pairs:
    - - 3
      - 0
    - - 6
      - 3
    as_absolute: true
- - orientation_change
  - step: 30
    keypoint_pairs:
    - - 3
      - 0
    - - 6
      - 3
    as_absolute: true
- - posture_angles
  - keypoint_pairs_1:
    - - 6
      - 3
    - - 3
      - 0
    - - 3
      - 0
    - - 6
      - 3
    - - 6
      - 3
    keypoint_pairs_2:
    - - 3
      - 0
    - - 3
      - 1
    - - 3
      - 2
    - - 6
      - 4
    - - 6
      - 5
    element_wise: true
dyadic:
- - target_velocity
  - step: 5
    keypoints_1:
    - 0
    - 3
    keypoint_pairs_2:
    - - 0
      - 0
    - - 0
      - 3
    - - 0
      - 6
    - - 3
      - 0
    - - 3
      - 3
    - - 3
      - 6
    discard: -rej
- - target_velocity
  - step: 15
    keypoints_1:
    - 0
    - 3
    keypoint_pairs_2:
    - - 0
      - 0
    - - 0
      - 3
    - - 0
      - 6
    - - 3
      - 0
    - - 3
      - 3
    - - 3
      - 6
    discard: -rej
- - target_velocity
  - step: 30
    keypoints_1:
    - 0
    - 3
    keypoint_pairs_2:
    - - 0
      - 0
    - - 0
      - 3
    - - 0
      - 6
    - - 3
      - 0
    - - 3
      - 3
    - - 3
      - 6
    discard: -rej
- - target_velocity
  - step: 5
    keypoints_1:
    - 0
    - 3
    keypoint_pairs_2:
    - - 0
      - 0
    - - 0
      - 3
    - - 0
      - 6
    - - 3
      - 0
    - - 3
      - 3
    - - 3
      - 6
    as_absolute: true
    discard: -proj
- - target_velocity
  - step: 15
    keypoints_1:
    - 0
    - 3
    keypoint_pairs_2:
    - - 0
      - 0
    - - 0
      - 3
    - - 0
      - 6
    - - 3
      - 0
    - - 3
      - 3
    - - 3
      - 6
    as_absolute: true
    discard: -proj
- - target_velocity
  - step: 30
    keypoints_1:
    - 0
    - 3
    keypoint_pairs_2:
    - - 0
      - 0
    - - 0
      - 3
    - - 0
      - 6
    - - 3
      - 0
    - - 3
      - 3
    - - 3
      - 6
    as_absolute: true
    discard: -proj
- - keypoint_distances
  - keypoints_1:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    keypoints_2:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
- - target_angles
  - keypoint_pairs_1:
    - - 3
      - 0
    - - 6
      - 3
    keypoints_2:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    as_absolute: true
- - posture_alignment
  - keypoint_pairs_1:
    - - 3
      - 0
    - - 6
      - 3
    keypoint_pairs_2:
    - - 3
      - 0
    - - 6
      - 3
